name: Run Candidate Transformer

on:
  workflow_dispatch:

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5

      with:
        python-version: "3.11"

    - run: pip install -r requirements.txt

    - name: Default Config
      run: |
        python main.py \
        --ats data/ats.json \
        --csv data/recruiter.csv \
        --notes data/notes.txt \
        --config configs/default.json

    - name: Custom Config
      run: |
        python main.py \
        --ats data/ats.json \
        --csv data/recruiter.csv \
        --notes data/notes.txt \
        --config configs/custom.json
